apiVersion: v1
kind: ConfigMap
metadata:
  name: ntp-cloud-init
  namespace: infrastructure
data:
  user-data: |
    #cloud-config
    hostname: ntp
    fqdn: ntp.BASE_DOMAIN
    manage_etc_hosts: true
    chpasswd:
      expire: false
      list: |
        root:changeme-ntp-root
    ssh_authorized_keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC... installer@staging
    packages:
      - chrony
      - firewalld
    write_files:
      - path: /etc/chrony.conf
        content: |
          local stratum 3 orphan
          allow NETWORK_CIDR
          bindaddress NTP_VM_IP
          makestep 1.0 3
          rtcsync
          driftfile /var/lib/chrony/drift
          logdir /var/log/chrony
    runcmd:
      - systemctl enable --now chronyd
      - firewall-cmd --permanent --add-service=ntp
      - firewall-cmd --reload
