#!/usr/bin/env bash
# Bastion DNS (dnsmasq) and NTP (chronyd) for the dark site (Lab 07).
#
# These services run for the life of the site: they are the MVP during install and the
# secondary resolver and time source afterwards, so a cold start never waits on VMs that
# need DNS and time to boot (ADR-07, FR-H12).
#
#   sudo ./scripts/02-bootstrap-dns-ntp.sh              configure, start, verify
#   ./scripts/02-bootstrap-dns-ntp.sh --print-config    print both files, change nothing
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=scripts/lib/common.sh
source "${SCRIPT_DIR}/lib/common.sh"

PRINT_ONLY=false
[[ "${1:-}" == "--print-config" ]] && PRINT_ONLY=true

load_env
validate_env --scope services   # site steps run before MACs, disks and the pull secret are known
[[ "${PRINT_ONLY}" == true ]] || check_root

CLUSTER_DOMAIN="${CLUSTER_NAME}.${BASE_DOMAIN}"

dnsmasq_config() {
  cat <<EOF
# OCP-V dark site DNS — generated by scripts/02-bootstrap-dns-ntp.sh from .env. Do not edit.
# Bind loopback too, so the bastion's own resolver (nameserver ${BASTION_IP} in its
# kickstart) is answered locally (FR-E5).
listen-address=127.0.0.1,${BASTION_IP}
bind-interfaces
# Dark site: no upstream resolvers; names under ${BASE_DOMAIN} are answered from here only.
no-resolv
local=/${BASE_DOMAIN}/
domain=${BASE_DOMAIN}

# host-record = A record plus the matching PTR, so reverse lookups work (FR-F1).
host-record=${BASTION_HOSTNAME}.${BASE_DOMAIN},${BASTION_IP}
host-record=${MIRROR_REGISTRY_HOSTNAME},${MIRROR_REGISTRY_IP}
host-record=${MW01_HOSTNAME}.${BASE_DOMAIN},${MW01_IP}
host-record=${MW02_HOSTNAME}.${BASE_DOMAIN},${MW02_IP}
host-record=${MW03_HOSTNAME}.${BASE_DOMAIN},${MW03_IP}
host-record=api.${CLUSTER_DOMAIN},${API_VIP}
host-record=api-int.${CLUSTER_DOMAIN},${API_VIP}

# address=/<domain>/ answers for the domain and every name below it, so this one line is
# the *.apps wildcard; a literal '*.' prefix is redundant at best (FR-F1).
address=/apps.${CLUSTER_DOMAIN}/${INGRESS_VIP}

# Steady-state service VMs (Lab 14), pre-provisioned so they resolve the moment they boot.
host-record=dns-a.${BASE_DOMAIN},${DNS_VM1_IP}
host-record=dns-b.${BASE_DOMAIN},${DNS_VM2_IP}
host-record=ntp.${BASE_DOMAIN},${NTP_VM_IP}
EOF
}

chrony_config() {
  echo "# OCP-V dark site NTP — generated by scripts/02-bootstrap-dns-ntp.sh from .env (TIME_SOURCE=${TIME_SOURCE}). Do not edit."
  if [[ "${TIME_SOURCE}" == "orphan" ]]; then
    echo "# LAB-GRADE: no reference clock. The site agrees with this host, not with UTC (Lab 07)."
  else
    echo "server ${TIME_SOURCE} iburst"
  fi
  cat <<EOF
# Keep serving at stratum 10 if the reference is lost, so nodes stay in agreement.
local stratum 10 orphan
allow ${MACHINE_NETWORK_CIDR}
makestep 1.0 3
rtcsync
driftfile /var/lib/chrony/drift
logdir /var/log/chrony
EOF
}

if [[ "${PRINT_ONLY}" == true ]]; then
  echo "### /etc/dnsmasq.d/ocp-v.conf"; dnsmasq_config
  echo; echo "### /etc/chrony.conf"; chrony_config
  exit 0
fi

# dnsmasq binds BASTION_IP explicitly (bind-interfaces), so the address must already be on a
# NIC; otherwise it fails with "cannot assign requested address" and nothing else explains why.
if ! ip -o -4 addr show | awk '{print $4}' | cut -d/ -f1 | grep -qxF "${BASTION_IP}"; then
  log_error "BASTION_IP=${BASTION_IP} is not configured on any interface of this host."
  log_error "Either fix BASTION_IP in .env (group D1), or give the NIC that address, e.g.:"
  log_error "  nmcli con mod <connection> ipv4.method manual ipv4.addresses ${BASTION_IP}/${MACHINE_NETWORK_CIDR#*/} ipv4.gateway ${NETWORK_GATEWAY} && nmcli con up <connection>"
  ip -br -4 addr >&2
  exit 1
fi

# The kickstart installs these from the DVD (Lab 04). A hand-installed bastion may lack them:
# install from whatever local repository is configured (the DVD repo from script 04b, or a
# mounted DVD); a dark site has no CDN, so a timeout here means "no local repo yet".
missing=()
for pkg in dnsmasq chrony bind-utils; do
  rpm -q "${pkg}" &>/dev/null || missing+=("${pkg}")
done
if (( ${#missing[@]} > 0 )); then
  log_info "Installing ${missing[*]} from the configured local repository"
  if ! timeout 300 dnf -y install "${missing[@]}"; then
    log_error "Could not install ${missing[*]}. They are on the RHEL 9 DVD (AppStream/BaseOS). Either:"
    log_error "  copy the DVD ISO to ${MIRROR_DIR}/rhel9-dvd.iso and run: sudo ./scripts/04b-serve-dvd-repo.sh"
    log_error "  or mount it: mount -o loop,ro <dvd.iso> /mnt && dnf -y --repofrompath=b,file:///mnt/BaseOS --repofrompath=a,file:///mnt/AppStream --nogpgcheck install ${missing[*]}"
    exit 1
  fi
fi

dnsmasq_config > /etc/dnsmasq.d/ocp-v.conf
dnsmasq --test --conf-file=/etc/dnsmasq.conf
chrony_config > /etc/chrony.conf
log_info "Wrote /etc/dnsmasq.d/ocp-v.conf and /etc/chrony.conf"

if systemctl is-active --quiet firewalld; then
  firewall-cmd --permanent --add-service=dns --add-service=ntp
  firewall-cmd --reload
fi

systemctl enable chronyd dnsmasq
systemctl restart chronyd dnsmasq

# VERIFY — compare answers with .env, not exit codes (FR-I2).
fails=0
verify() {
  local desc=$1; shift
  if "$@"; then log_info "PASS: ${desc}"; else log_error "FAIL: ${desc}"; fails=$((fails + 1)); fi
}
verify "registry A via loopback resolver" expect_dns 127.0.0.1 "${MIRROR_REGISTRY_HOSTNAME}" "${MIRROR_REGISTRY_IP}"
verify "api A -> API_VIP" expect_dns "${BASTION_IP}" "api.${CLUSTER_DOMAIN}" "${API_VIP}"
verify "api-int A -> API_VIP" expect_dns "${BASTION_IP}" "api-int.${CLUSTER_DOMAIN}" "${API_VIP}"
verify "*.apps wildcard -> INGRESS_VIP" expect_dns "${BASTION_IP}" "console-openshift-console.apps.${CLUSTER_DOMAIN}" "${INGRESS_VIP}"
verify "${MW01_HOSTNAME} PTR" expect_ptr "${BASTION_IP}" "${MW01_IP}" "${MW01_HOSTNAME}.${BASE_DOMAIN}"
verify "chronyd serves time (offset < 1 s)" ntp_offset_ok "${BASTION_IP}"
if [[ "${TIME_SOURCE}" != "orphan" ]] && ! ntp_offset_ok "${TIME_SOURCE}"; then
  # Not fatal: chronyd keeps serving its own clock (local stratum 10 orphan) and locks on to
  # TIME_SOURCE as soon as it answers. Until then the site runs on the bastion's clock (step 7.0).
  log_warn "TIME_SOURCE ${TIME_SOURCE} does not answer NTP from here (route via ${NETWORK_GATEWAY}? UDP 123 open?)."
  log_warn "The bastion serves its own clock until it does; check later with: chronyc sources"
fi
if (( fails > 0 )); then
  log_error "${fails} check(s) failed"
  exit 1
fi

log_info "PASS: bastion DNS ${BASTION_IP}:53 and NTP ${BASTION_IP}:123 serve .env values"
log_info "Nodes receive these through agent-config.yaml (dns-resolver, additionalNTPSources) in Lab 08."
log_info "Next: ./scripts/03-generate-install-config.sh"
