#!/usr/bin/env bash
# Make the bastion the site's temporary DNS server (dnsmasq) and NTP server (chronyd).
#
# A DNS or NTP server does not know whether clients list it first or second:
# "primary" vs "secondary" is the ORDER of servers in each node's resolver and chrony
# configuration (agent-config.yaml), not a property of this server. The same
# configuration therefore serves the bastion's whole life: sole server during install,
# fallback during cutover. See docs/BASTION-LIFECYCLE.md.
#
# Usage:
#   sudo ./scripts/02-bootstrap-dns-ntp.sh                      configure, start, verify
#   sudo ./scripts/02-bootstrap-dns-ntp.sh --set-time 'YYYY-MM-DD HH:MM:SS'
#                                                               set the clock (UTC) first
#        ./scripts/02-bootstrap-dns-ntp.sh --verify             checks only, no changes
#        ./scripts/02-bootstrap-dns-ntp.sh --dry-run            print generated configs, no changes
#        ./scripts/02-bootstrap-dns-ntp.sh --export-hosts       print /etc/hosts-format records
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck disable=SC1091
source "${SCRIPT_DIR}/lib/common.sh"

DNSMASQ_MAIN=/etc/dnsmasq.conf
DNSMASQ_CONF=/etc/dnsmasq.d/ocp-v.conf
CHRONY_CONF=/etc/chrony.conf

MODE=apply
SET_TIME=""
while [[ $# -gt 0 ]]; do
  case "$1" in
    --set-time)     SET_TIME="${2:?--set-time needs a UTC time, e.g. --set-time '2026-10-06 14:30:00'}"; shift 2 ;;
    --verify)       MODE=verify; shift ;;
    --dry-run)      MODE=dry-run; shift ;;
    --export-hosts) MODE=export-hosts; shift ;;
    -h|--help)      sed -n '2,16p' "$0"; exit 0 ;;
    *)              log_error "Unknown option: $1 (see --help)"; exit 1 ;;
  esac
done

load_env

# --- Inputs -------------------------------------------------------------------

require_vars() {
  local v missing=()
  for v in "$@"; do [[ -n "${!v:-}" ]] || missing+=("$v"); done
  if (( ${#missing[@]} )); then
    log_error "Missing values in .env: ${missing[*]}"
    exit 1
  fi
}
require_vars BASE_DOMAIN CLUSTER_NAME BASTION_IP MIRROR_REGISTRY_IP NETWORK_CIDR \
  API_VIP INGRESS_VIP CP01_IP CP02_IP CP03_IP

CLUSTER_DOMAIN="${CLUSTER_NAME}.${BASE_DOMAIN}"
REGISTRY_FQDN="${MIRROR_REGISTRY_HOSTNAME:-registry.${BASE_DOMAIN}}"

# One table ("fqdn ip") drives the dnsmasq config, the hosts export and verification.
# Optional hosts (workers, future DNS/NTP VMs) are skipped when their IP is empty.
RECORDS=()
add_record() {
  [[ -n "${2:-}" ]] || return 0
  if [[ ! "$2" =~ ^([0-9]{1,3}\.){3}[0-9]{1,3}$ ]]; then
    log_error "Not an IPv4 address for $1: '$2' (check .env)"
    exit 1
  fi
  RECORDS+=("$1 $2")
}
add_record "bastion.${BASE_DOMAIN}"    "${BASTION_IP}"
add_record "${REGISTRY_FQDN}"          "${MIRROR_REGISTRY_IP}"
add_record "gw.${BASE_DOMAIN}"         "${NETWORK_GATEWAY:-}"
add_record "api.${CLUSTER_DOMAIN}"     "${API_VIP}"
add_record "api-int.${CLUSTER_DOMAIN}" "${API_VIP}"
add_record "cp01.${BASE_DOMAIN}"       "${CP01_IP}"
add_record "cp02.${BASE_DOMAIN}"       "${CP02_IP}"
add_record "cp03.${BASE_DOMAIN}"       "${CP03_IP}"
add_record "wk01.${BASE_DOMAIN}"       "${WK01_IP:-}"
add_record "wk02.${BASE_DOMAIN}"       "${WK02_IP:-}"
add_record "dns.${BASE_DOMAIN}"        "${DNS_VM_IP:-}"
add_record "ntp.${BASE_DOMAIN}"        "${NTP_VM_IP:-}"
add_record "apps.${CLUSTER_DOMAIN}"    "${INGRESS_VIP}"   # validated here; rendered as a wildcard

# --- Renderers ----------------------------------------------------------------

render_dnsmasq() {
  cat <<EOF
# Generated by scripts/02-bootstrap-dns-ntp.sh from .env. Re-run the script; do not edit.
# Temporary DNS for ${CLUSTER_DOMAIN} on the bastion. No upstream servers (dark site).

# Loopback (the bastion's own lookups) and the install-network address only.
# bind-interfaces avoids clashing with other local resolvers (systemd-resolved, libvirt).
listen-address=127.0.0.1,${BASTION_IP}
bind-interfaces

# This file is the single source of truth: no upstream servers, no /etc/hosts.
no-resolv
no-hosts
domain-needed
bogus-priv
# Unknown names in our domain get NXDOMAIN instead of REFUSED.
local=/${BASE_DOMAIN}/

# Application routes: apps.<cluster>.<domain> and every name below it.
# No leading '*': wildcard syntax differs across dnsmasq versions; this form works in all.
address=/apps.${CLUSTER_DOMAIN}/${INGRESS_VIP}

# Hosts and VIPs: A and PTR records.
EOF
  local r
  for r in "${RECORDS[@]}"; do
    [[ "${r% *}" == "apps.${CLUSTER_DOMAIN}" ]] && continue
    printf 'host-record=%s,%s\n' "${r% *}" "${r#* }"
  done
  cat <<'EOF'

# Query log goes to the journal: journalctl -u dnsmasq
log-queries
EOF
}

render_dnsmasq_main() {
  cat <<EOF
# Managed by scripts/02-bootstrap-dns-ntp.sh (original saved as ${DNSMASQ_MAIN}.orig).
# All settings live in ${DNSMASQ_CONF}.
user=dnsmasq
group=dnsmasq
conf-dir=/etc/dnsmasq.d,.rpmnew,.rpmsave,.rpmorig
EOF
}

render_chrony() {
  cat <<EOF
# Generated by scripts/02-bootstrap-dns-ntp.sh from .env (original saved as ${CHRONY_CONF}.orig).
# The bastion is the site's temporary time authority. No upstream servers (dark site).
# The local clock is served at stratum 10, so any later real source (lower stratum) wins.
local stratum 10
allow ${NETWORK_CIDR}
makestep 1.0 3
rtcsync
driftfile /var/lib/chrony/drift
logdir /var/log/chrony
EOF
}

render_hosts() {
  local r
  for r in "${RECORDS[@]}"; do
    [[ "${r% *}" == "apps.${CLUSTER_DOMAIN}" ]] && continue
    printf '%-16s %s %s\n' "${r#* }" "${r% *}" "${r%%.*}"
  done
  # /etc/hosts has no wildcards: list the routes the installer and console need.
  local app
  for app in console-openshift-console oauth-openshift downloads-openshift-console; do
    printf '%-16s %s\n' "${INGRESS_VIP}" "${app}.apps.${CLUSTER_DOMAIN}"
  done
}

# --- Verification -------------------------------------------------------------

VERIFY_FAILS=0
pass() { echo "  [PASS] $*"; }
fail() { echo "  [FAIL] $*"; VERIFY_FAILS=$((VERIFY_FAILS + 1)); }

dns_expect() {   # dns_expect <server> <name> <expected> [type]
  local got
  got=$(dig +short +time=2 +tries=1 @"$1" "$2" "${4:-A}" 2>/dev/null | tail -n1 || true)
  if [[ "$got" == "$3" ]]; then pass "DNS @$1  $2 -> $3"; else fail "DNS @$1  $2: expected $3, got '${got:-no answer}'"; fi
}

verify() {
  require_cmd dig chronyc chronyd ss
  echo "=== DNS (dnsmasq) ==="
  local r
  for r in "${RECORDS[@]}"; do
    [[ "${r% *}" == "apps.${CLUSTER_DOMAIN}" ]] && continue
    dns_expect "${BASTION_IP}" "${r% *}" "${r#* }"
  done
  dns_expect "${BASTION_IP}" "console-openshift-console.apps.${CLUSTER_DOMAIN}" "${INGRESS_VIP}"
  dns_expect "${BASTION_IP}" "$(printf '%s' "${CP01_IP}" | awk -F. '{print $4"."$3"."$2"."$1}').in-addr.arpa" \
    "cp01.${BASE_DOMAIN}." PTR
  dns_expect 127.0.0.1 "api.${CLUSTER_DOMAIN}" "${API_VIP}"

  echo "=== NTP (chronyd) ==="
  if ss -H -lun 'sport = :123' | grep -q .; then pass "chronyd listening on UDP 123"; else fail "nothing listening on UDP 123"; fi
  local tracking
  tracking=$(chronyc -n tracking 2>/dev/null || true)
  if grep -q 'Leap status *: Normal' <<<"$tracking"; then
    pass "chronyd serving: $(grep -E '^Stratum' <<<"$tracking" | tr -s ' ')"
  else
    fail "chronyd not serving time yet (chronyc tracking: $(grep -E '^Leap status' <<<"$tracking" | tr -s ' '))"
  fi
  # Over-the-wire probe: a one-shot NTP client query to BASTION_IP (measures only, never sets the clock).
  if [[ $EUID -eq 0 ]]; then
    local probe
    if probe=$(timeout 20 chronyd -Q -t 10 'port 0' 'cmdport 0' 'pidfile /run/chronyd-verify.pid' \
                 "server ${BASTION_IP} iburst maxsamples 4" 2>&1); then
      pass "NTP query to ${BASTION_IP}:123 answered ($(grep -o 'wrong by [-0-9.]* seconds' <<<"$probe" || echo ok))"
    else
      fail "NTP query to ${BASTION_IP}:123 got no answer (firewall? allow ${NETWORK_CIDR}?)"
    fi
  else
    echo "  [SKIP] over-the-wire NTP query (run with sudo to include it)"
  fi

  echo
  if (( VERIFY_FAILS == 0 )); then log_info "All checks passed"; else log_error "${VERIFY_FAILS} check(s) failed"; fi
  return $(( VERIFY_FAILS > 0 ))
}

# --- Modes that change nothing -------------------------------------------------

case "$MODE" in
  export-hosts) render_hosts; exit 0 ;;
  dry-run)
    echo "### ${DNSMASQ_MAIN}";  render_dnsmasq_main; echo
    echo "### ${DNSMASQ_CONF}";  render_dnsmasq;      echo
    echo "### ${CHRONY_CONF}";   render_chrony
    exit 0 ;;
  verify) verify; exit $? ;;
esac

# --- Apply --------------------------------------------------------------------

check_root

if ! ip -o -4 addr show | awk '{split($4, a, "/"); print a[1]}' | grep -qxF "${BASTION_IP}"; then
  log_error "BASTION_IP=${BASTION_IP} is not configured on any interface of this host."
  log_error "Fix the bastion's address (nmcli) or BASTION_IP in .env, then re-run."
  exit 1
fi

missing=()
command -v dnsmasq &>/dev/null || missing+=(dnsmasq)
command -v chronyd &>/dev/null || missing+=(chrony)
command -v dig     &>/dev/null || missing+=(bind-utils)
if (( ${#missing[@]} )); then
  log_info "Installing: ${missing[*]}"
  if ! dnf install -y "${missing[@]}"; then
    log_error "dnf could not install ${missing[*]}. In a dark site, mount the RHEL DVD as a local"
    log_error "repository first (docs/BASTION-LIFECYCLE.md, Phase 1 step 4)."
    exit 1
  fi
fi
require_cmd ss ip

# Another DNS server already bound to one of our addresses (or to all addresses) would
# make dnsmasq fail to start. Other dnsmasq instances (e.g. libvirt) on other IPs are fine.
conflicts=$(ss -H -lunp 'sport = :53' \
  | awk -v b="${BASTION_IP}:53" '$4=="127.0.0.1:53" || $4==b || $4=="0.0.0.0:53" || $4=="*:53" || $4=="[::]:53"' \
  | grep -v '"dnsmasq"' || true)
if [[ -n "$conflicts" ]]; then
  log_error "Another process already listens on port 53 at an address dnsmasq needs:"
  echo "$conflicts" >&2
  log_error "Stop it (e.g. 'systemctl disable --now named'), then re-run."
  exit 1
fi

if [[ -n "$SET_TIME" ]]; then
  if ! date -u -d "$SET_TIME" &>/dev/null; then
    log_error "Cannot parse --set-time '$SET_TIME' (expected 'YYYY-MM-DD HH:MM:SS', UTC)"
    exit 1
  fi
  systemctl stop chronyd 2>/dev/null || true
  date -u -s "$SET_TIME" >/dev/null
  hwclock --systohc --utc 2>/dev/null || log_warn "Could not update the hardware clock (hwclock)"
  log_info "Clock set to $(date -u '+%F %T') UTC"
fi

backup_once() { if [[ -f "$1" && ! -f "$1.orig" ]]; then cp -p "$1" "$1.orig"; fi; }

backup_once "$DNSMASQ_MAIN"
backup_once "$CHRONY_CONF"
mkdir -p "$(dirname "$DNSMASQ_CONF")"
render_dnsmasq_main > "$DNSMASQ_MAIN"
render_dnsmasq      > "$DNSMASQ_CONF"
render_chrony       > "$CHRONY_CONF"
restorecon -F "$DNSMASQ_MAIN" "$DNSMASQ_CONF" "$CHRONY_CONF" 2>/dev/null || true
log_info "Wrote ${DNSMASQ_CONF}, ${DNSMASQ_MAIN} and ${CHRONY_CONF}"

if ! dnsmasq --test 2>&1; then
  log_error "dnsmasq rejected the generated configuration (see above). Not restarting."
  exit 1
fi

if systemctl is-active --quiet firewalld; then
  firewall-cmd --quiet --permanent --add-service=dns
  firewall-cmd --quiet --permanent --add-service=ntp
  firewall-cmd --quiet --reload
  log_info "firewalld: dns (53) and ntp (123) open"
fi

systemctl enable --quiet dnsmasq chronyd
systemctl restart chronyd dnsmasq     # restart, not start: re-runs must apply new config
for svc in chronyd dnsmasq; do
  if ! systemctl is-active --quiet "$svc"; then
    log_error "$svc failed to start:"
    journalctl -u "$svc" -n 20 --no-pager >&2 || true
    exit 1
  fi
done

log_info "Bastion clock: $(date -u '+%F %T') UTC. If that is wrong, re-run with --set-time."
sleep 3   # let chronyd select its local reference before verifying
echo
verify || exit 1

cat <<EOF

=== The bastion is serving DNS (${BASTION_IP}:53) and NTP (${BASTION_IP}:123) ===
Nodes decide whether this server is their first or second choice. Until the permanent
servers pass the parity check (docs/BASTION-LIFECYCLE.md, Phase 7), list ONLY the bastion:
  agent-config.yaml, each host:  networkConfig.dns-resolver.config.server: [${BASTION_IP}]
  agent-config.yaml, top level:  additionalNTPSources: [${BASTION_IP}]
Next: ./scripts/03-generate-install-config.sh
EOF
