#!/usr/bin/env bash
# Serve the RHEL 9 DVD's BaseOS and AppStream from the bastion (Lab 06 step 6.5, FR-H3).
#
#   sudo ./scripts/04b-serve-dvd-repo.sh
#
# One loop-mounted ISO, two consumers:
#   - the bastion itself, via file:// dnf repos (it was installed offline and has none);
#   - the DNS and NTP VMs (Lab 14), via http://${BASTION_IP}/rhel9/ in their cloud-init,
#     because the guest image lacks bind and a dark site has no CDN.
# Expects the DVD at ${MIRROR_DIR}/rhel9-dvd.iso (copied from the transfer media).
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=scripts/lib/common.sh
source "${SCRIPT_DIR}/lib/common.sh"

load_env
validate_env
check_root

ISO="${MIRROR_DIR}/rhel9-dvd.iso"
WEBROOT=/var/www/html/rhel9
if [[ ! -f "${ISO}" ]]; then
  log_error "${ISO} not found; copy the RHEL 9 DVD from the transfer media (Lab 06 step 6.4)"
  exit 1
fi

mkdir -p "${WEBROOT}"
# context= labels the read-only ISO for httpd; an iso9660 mount is otherwise unreadable
# to httpd under SELinux enforcing.
FSTAB_LINE="${ISO} ${WEBROOT} iso9660 loop,ro,nofail,context=system_u:object_r:httpd_sys_content_t:s0 0 0"
grep -qF "${ISO} ${WEBROOT} " /etc/fstab || echo "${FSTAB_LINE}" >> /etc/fstab
mountpoint -q "${WEBROOT}" || mount "${WEBROOT}"

cat > /etc/yum.repos.d/rhel9-dvd.repo <<EOF
# Generated by scripts/04b-serve-dvd-repo.sh: the RHEL 9 DVD as the bastion's only repo.
[rhel9-dvd-baseos]
name=RHEL 9 DVD BaseOS
baseurl=file://${WEBROOT}/BaseOS
enabled=1
gpgcheck=1
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-redhat-release

[rhel9-dvd-appstream]
name=RHEL 9 DVD AppStream
baseurl=file://${WEBROOT}/AppStream
enabled=1
gpgcheck=1
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-redhat-release
EOF

rpm -q httpd &>/dev/null || dnf -y install httpd
systemctl enable --now httpd
if systemctl is-active --quiet firewalld; then
  firewall-cmd --permanent --add-service=http
  firewall-cmd --reload
fi

# VERIFY: both repos answer over HTTP from the machine-network address the VMs will use.
for repo in BaseOS AppStream; do
  code="$(curl -s -o /dev/null -w '%{http_code}' "http://${BASTION_IP}/rhel9/${repo}/repodata/repomd.xml")"
  if [[ "${code}" != "200" ]]; then
    log_error "http://${BASTION_IP}/rhel9/${repo}/repodata/repomd.xml returned ${code}, expected 200"
    exit 1
  fi
done
dnf -q repolist --enabled
log_info "PASS: RHEL 9 DVD served at http://${BASTION_IP}/rhel9/{BaseOS,AppStream} and used by local dnf"
